-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 22:24:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Parqueadero_Lot_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Parqueadero_Lot_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Parqueadero_Lot_DB` DEFAULT CHARACTER SET utf8 ;
USE `Parqueadero_Lot_DB` ;

-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Tipo_Identificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Tipo_Identificacion` (
  `idTipo_Identificacion` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_Identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `Identificacion` VARCHAR(45) NOT NULL,
  `Primer_Nombre` VARCHAR(45) NOT NULL,
  `Segundo_Nombre` VARCHAR(45) NULL,
  `Primer_Apellido` VARCHAR(45) NOT NULL,
  `Segundo_Apellido` VARCHAR(45) NULL,
  `Telefono` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Tipo_Identificacion_idTipo_Identificacion` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Persona_Tipo_Identificacion_idx` (`Tipo_Identificacion_idTipo_Identificacion` ASC) ,
  CONSTRAINT `fk_Persona_Tipo_Identificacion`
    FOREIGN KEY (`Tipo_Identificacion_idTipo_Identificacion`)
    REFERENCES `Parqueadero_Lot_DB`.`Tipo_Identificacion` (`idTipo_Identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Parqueadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Parqueadero` (
  `idParqueadero` INT NOT NULL AUTO_INCREMENT,
  `Clase` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `CoordenadasGPS` VARCHAR(45) NOT NULL,
  `ModoControl` VARCHAR(45) NULL,
  PRIMARY KEY (`idParqueadero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `Persona_idPersona` INT NOT NULL,
  `Parqueadero_idParqueadero` INT NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_Administrador_Persona1_idx` (`Persona_idPersona` ASC) ,
  INDEX `fk_Administrador_Parqueadero1_idx` (`Parqueadero_idParqueadero` ASC) ,
  CONSTRAINT `fk_Administrador_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Parqueadero_Lot_DB`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Administrador_Parqueadero1`
    FOREIGN KEY (`Parqueadero_idParqueadero`)
    REFERENCES `Parqueadero_Lot_DB`.`Parqueadero` (`idParqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Colaborador` (
  `idColaborador` INT NOT NULL AUTO_INCREMENT,
  `Persona_idPersona` INT NOT NULL,
  `Parqueadero_idParqueadero` INT NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idColaborador`),
  INDEX `fk_Colaborador_Parqueadero1_idx` (`Parqueadero_idParqueadero` ASC) ,
  INDEX `fk_Colaborador_Persona1_idx` (`Persona_idPersona` ASC) ,
  CONSTRAINT `fk_Colaborador_Parqueadero1`
    FOREIGN KEY (`Parqueadero_idParqueadero`)
    REFERENCES `Parqueadero_Lot_DB`.`Parqueadero` (`idParqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Parqueadero_Lot_DB`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Tarifa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Tarifa` (
  `idTarifa` INT NOT NULL AUTO_INCREMENT,
  `ValorPorHora` DECIMAL(10,2) NOT NULL,
  `ValorHoraAdicional` DECIMAL(10,2) NOT NULL,
  `Parqueadero_idParqueadero` INT NOT NULL,
  PRIMARY KEY (`idTarifa`),
  INDEX `fk_Tarifa_Parqueadero1_idx` (`Parqueadero_idParqueadero` ASC) ,
  CONSTRAINT `fk_Tarifa_Parqueadero1`
    FOREIGN KEY (`Parqueadero_idParqueadero`)
    REFERENCES `Parqueadero_Lot_DB`.`Parqueadero` (`idParqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Vehiculo` (
  `idVehiculo` INT NOT NULL AUTO_INCREMENT,
  `NumeroPlaca` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idVehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(255) NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `Parqueadero_idParqueadero` INT NOT NULL,
  `Vehiculo_idVehiculo` INT NOT NULL,
  `FechaNacimiento` DATE NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Persona1_idx` (`Persona_idPersona` ASC) ,
  INDEX `fk_Usuario_Parqueadero1_idx` (`Parqueadero_idParqueadero` ASC) ,
  INDEX `fk_Usuario_Vehiculo1_idx` (`Vehiculo_idVehiculo` ASC) ,
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Parqueadero_Lot_DB`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Parqueadero1`
    FOREIGN KEY (`Parqueadero_idParqueadero`)
    REFERENCES `Parqueadero_Lot_DB`.`Parqueadero` (`idParqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Vehiculo1`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `Parqueadero_Lot_DB`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Configuracion` (
  `idConfiguracion` INT NOT NULL AUTO_INCREMENT,
  `Parqueadero_idParqueadero` INT NOT NULL,
  `ClaveAcceso` VARCHAR(45) NOT NULL,
  `HorarioAtencion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idConfiguracion`),
  INDEX `fk_Configuracion_Parqueadero1_idx` (`Parqueadero_idParqueadero` ASC) ,
  CONSTRAINT `fk_Configuracion_Parqueadero1`
    FOREIGN KEY (`Parqueadero_idParqueadero`)
    REFERENCES `Parqueadero_Lot_DB`.`Parqueadero` (`idParqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Parqueo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Parqueo` (
  `idParqueo` INT NOT NULL AUTO_INCREMENT,
  `Vehiculo_idVehiculo` INT NOT NULL,
  `HoraIngreso` VARCHAR(45) NOT NULL,
  `HoraSalida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParqueo`),
  INDEX `fk_Parqueo_Vehiculo1_idx` (`Vehiculo_idVehiculo` ASC) ,
  CONSTRAINT `fk_Parqueo_Vehiculo1`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `Parqueadero_Lot_DB`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Reporte` (
  `idReporte` INT NOT NULL AUTO_INCREMENT,
  `NumeroPlaca` VARCHAR(15) NOT NULL,
  `HoraIngreso` DATETIME NOT NULL,
  `TiempoTranscurrido` TIME NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `descripcion` VARCHAR(45) NULL COMMENT 'Se genera un reporte por el valor total en base al tiempo de uso.',
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idReporte`),
  INDEX `fk_Reporte_Persona1_idx` (`Persona_idPersona` ASC) ,
  CONSTRAINT `fk_Reporte_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `Parqueadero_Lot_DB`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parqueadero_Lot_DB`.`Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parqueadero_Lot_DB`.`Recibo` (
  `idRecibo` INT NOT NULL AUTO_INCREMENT,
  `HoraIngreso` DATETIME NOT NULL,
  `HoraSalida` DATETIME NOT NULL,
  `TiempoTranscurrido` TIME NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `ValorHora` DECIMAL(10,2) NOT NULL,
  `ValorHoraAdicional` DECIMAL(10,2) NOT NULL,
  `Parqueo_idParqueo` INT NOT NULL,
  PRIMARY KEY (`idRecibo`),
  INDEX `fk_Recibo_Parqueo1_idx` (`Parqueo_idParqueo` ASC) ,
  CONSTRAINT `fk_Recibo_Parqueo1`
    FOREIGN KEY (`Parqueo_idParqueo`)
    REFERENCES `Parqueadero_Lot_DB`.`Parqueo` (`idParqueo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
